apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: Cluster-$CIRCLE_WORKFLOW_ID
  region: us-west-1
  tags:
    project: project5

iam:
  withOIDC: true

nodeGroups:
  - name: flask-$CIRCLE_WORKFLOW_ID
    instanceType: t2.small
    amiFamily: AmazonLinux2
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    volumeSize: 80
    ssh:
      allow: true
      publicKeyName: udacity