version: 2.1

commands:

jobs:
    linting-app-code:
      docker:
      - image: python:3.7.3-stretch
      working_directory: ~/repo
      steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            make install
      - run:
          name: FAIL lint on the Dockerfile
          command: |          
            make lint
            return 1


workflows:
  default:
    jobs:
      - linting-app-code
