version: 2.1

commands:

jobs:
    linting-app-code:
      docker:
      - image: python:3.7.3-stretch
      working_directory: ~/repo
      steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
      - run:
          name: Lint the Dockerfile
          command: |          
            . venv/bin/activate
            make lint
            RESULT=$?
            if [ ${RESULT} -eq 0 ]
            then
              echo "linting success"
            else
              echo "linting failed"
            fi

    push-docker-image-to-image-repo:
      docker:
      - image: circleci/golang:1.15
      working_directory: ~/repo
      steps:
      - setup_remote_docker:
          version: 19.03.13
      - checkout
      - run:
          name: Run Docker Build on the app
          command: |
            docker build --tag project5 .
            docker image ls

workflows:
  default:
    jobs:
      - linting-app-code