version: 2.1

commands:

jobs:
    check-docker-code:
      docker:
      - image: python:3.7.3-stretch
      working_directory: ~/project/
      steps:
      - checkout
      - run:
          name: Installing Linters
          command: |
            make install
      - run:
          name: run lint on Dockerfile
          command: |          
            make lint
            RESULT=$?
            if [ ${RESULT} -eq 0 ]; then
              echo "successfully linted files - proceeding to build image"
            else
              echo "failed to lint files - please fix and try again"
            fi


workflows:
  default:
    jobs:
      - check-docker-code
