version: 2.1

commands:

jobs:
  linting-app-code:
    docker:
    - image: python:3.7.3-stretch
    working_directory: ~/repo
    steps:
    - checkout
    - run:
      name: install dependencies
      command: |
        make install
    - run:
      name: lint Dockerfile
      command: |
        make lint



workflows:
  default:
    jobs:
      - linting-app-code
