apiVersion: apps/v1
kind: Deployment
metadata:
  name: project5
  labels:
    app: project5
  namespace: default
spec:
  selector:
    matchLabels:
      app: project5
  replicas: 2
  template:
    metadata:
      labels:
        app: project5
    spec:
      containers:
      - name: project5
        image: sritchie1305/project5
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: project5
  labels:
    name: project5
spec:
  selector:
    app: project5
  ports:
    - name: http
      port: 8000
      targetPort: 80
  type: LoadBalancer